const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const scoreEl = document.querySelector('#score');
const coinsEl = document.querySelector('#coins');
const timerEl = document.querySelector('#timer');
const heartsEl = document.querySelector('#hearts');
const progressEl = document.querySelector('#progress');
const startScreen = document.querySelector('#start-screen');
const endScreen = document.querySelector('#end-screen');
const keys = {};
const worldWidth = 3600;
const initialCoins = [{ x: 420, y: 420 }, { x: 590, y: 300 }, { x: 810, y: 400 }, { x: 1040, y: 280 }, { x: 1240, y: 430 }, { x: 1510, y: 335 }, { x: 1720, y: 245 }, { x: 2010, y: 395 }, { x: 2260, y: 290 }, { x: 2560, y: 420 }, { x: 2850, y: 300 }, { x: 3160, y: 385 }];
const platforms = [{ x: 0, y: 560, w: 780, h: 80 }, { x: 870, y: 510, w: 350, h: 130 }, { x: 1300, y: 560, w: 560, h: 80 }, { x: 1940, y: 470, w: 350, h: 170 }, { x: 2380, y: 560, w: 650, h: 80 }, { x: 3100, y: 500, w: 500, h: 140 }, { x: 520, y: 380, w: 160, h: 20 }, { x: 970, y: 350, w: 160, h: 20 }, { x: 1450, y: 420, w: 160, h: 20 }, { x: 2110, y: 300, w: 150, h: 20 }, { x: 2630, y: 370, w: 180, h: 20 }];
let player, coins, enemies, camera, score, lives, elapsed, running, lastTime, animationId;

function resetGame() { player = { x: 90, y: 450, w: 34, h: 52, vx: 0, vy: 0, grounded: false, invincible: 0 }; coins = initialCoins.map((coin) => ({ ...coin, collected: false, spin: Math.random() * 6 })); enemies = [{ x: 690, y: 520, w: 38, h: 40, vx: 1.1, left: 640, right: 750, alive: true }, { x: 1090, y: 470, w: 38, h: 40, vx: -1.2, left: 900, right: 1170, alive: true }, { x: 1640, y: 520, w: 38, h: 40, vx: 1.3, left: 1400, right: 1800, alive: true }, { x: 2480, y: 520, w: 38, h: 40, vx: -1.5, left: 2400, right: 2900, alive: true }, { x: 3260, y: 460, w: 42, h: 40, vx: 1.1, left: 3140, right: 3500, alive: true }]; camera = 0; score = 0; lives = 3; elapsed = 0; updateHud(); }
function startGame() { cancelAnimationFrame(animationId); resetGame(); running = true; startScreen.classList.add('hidden'); endScreen.classList.add('hidden'); lastTime = performance.now(); animationId = requestAnimationFrame(loop); }
function finish(won) { running = false; cancelAnimationFrame(animationId); document.querySelector('#result-kicker').textContent = won ? 'Trail complete' : 'The jungle waits'; document.querySelector('#result-title').textContent = won ? 'You found the light.' : 'Keep your footing.'; document.querySelector('#result-copy').textContent = won ? 'The ancient gate opens for a brave explorer.' : 'Every great dash has a second run in it.'; document.querySelector('#final-score').textContent = String(score).padStart(4, '0'); document.querySelector('#final-coins').textContent = `${coins.filter((coin) => coin.collected).length} / ${coins.length}`; document.querySelector('#final-time').textContent = `${Math.ceil(elapsed)}s`; endScreen.classList.remove('hidden'); }
function updateHud() { const collected = coins.filter((coin) => coin.collected).length; scoreEl.textContent = String(score).padStart(4, '0'); coinsEl.textContent = `${collected} / ${coins.length}`; timerEl.textContent = Math.max(0, Math.ceil(90 - elapsed)); heartsEl.textContent = `${'♥ '.repeat(lives).trim()}${' ♡'.repeat(3 - lives)}`; progressEl.textContent = `${Math.min(100, Math.floor((player.x / (worldWidth - 220)) * 100))}%`; }
function overlaps(a, b) { return a.x < b.x + b.w && a.x + a.w > b.x && a.y < b.y + b.h && a.y + a.h > b.y; }
function update(dt) { elapsed += dt; if (elapsed >= 90) return finish(false); const direction = (keys.ArrowRight || keys.d ? 1 : 0) - (keys.ArrowLeft || keys.a ? 1 : 0); player.vx += (direction * 0.7 - player.vx * 0.16) * dt * 60; player.vx = Math.max(-5.5, Math.min(5.5, player.vx)); player.vy += 0.65 * dt * 60; player.x += player.vx * dt * 60; player.y += player.vy * dt * 60; player.x = Math.max(0, Math.min(worldWidth - 110, player.x)); if (player.y > 700) hurt();
  for (const platform of platforms) { if (player.vy >= 0 && player.x + player.w > platform.x && player.x < platform.x + platform.w && player.y + player.h >= platform.y && player.y + player.h - player.vy * dt * 60 <= platform.y + 8) { player.y = platform.y - player.h; player.vy = 0; player.grounded = true; } }
  if (player.y + player.h < 550) player.grounded = false; for (const coin of coins) { coin.spin += dt * 5; if (!coin.collected && Math.abs(player.x + player.w / 2 - coin.x) < 27 && Math.abs(player.y + player.h / 2 - coin.y) < 35) { coin.collected = true; score += 100; } }
  for (const enemy of enemies) { if (!enemy.alive) continue; enemy.x += enemy.vx * dt * 60; if (enemy.x < enemy.left || enemy.x > enemy.right) enemy.vx *= -1; if (overlaps(player, enemy)) { if (player.vy > 1 && player.y + player.h < enemy.y + 20) { enemy.alive = false; player.vy = -8; score += 250; } else if (player.invincible <= 0) hurt(); } } player.invincible = Math.max(0, player.invincible - dt); camera += (Math.max(0, player.x - camera - 220) - camera) * 0.08; if (player.x > 3370) finish(true); updateHud(); }
function hurt() { lives -= 1; player.invincible = 1.4; player.vy = -8; player.x = Math.max(40, player.x - 90); if (lives <= 0) finish(false); }
function draw() { const gradient = ctx.createLinearGradient(0, 0, 0, 640); gradient.addColorStop(0, '#83c8b0'); gradient.addColorStop(1, '#d4e79e'); ctx.fillStyle = gradient; ctx.fillRect(0, 0, 1280, 640); drawBackground(); ctx.save(); ctx.translate(-camera, 0); for (const platform of platforms) drawPlatform(platform); for (const coin of coins) if (!coin.collected) drawCoin(coin); for (const enemy of enemies) if (enemy.alive) drawEnemy(enemy); drawFlag(); if (player.invincible <= 0 || Math.floor(player.invincible * 10) % 2) drawPlayer(); ctx.restore(); }
function drawBackground() { ctx.fillStyle = '#66a88e'; for (let x = -((camera * .18) % 240) - 240; x < 1500; x += 240) { ctx.beginPath(); ctx.arc(x + 100, 210, 130, Math.PI, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#77b499'; ctx.beginPath(); ctx.arc(x + 195, 275, 150, Math.PI, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#66a88e'; } ctx.fillStyle = '#f2d66d'; ctx.globalAlpha = .75; ctx.beginPath(); ctx.arc(1040 - camera * .08, 105, 48, 0, Math.PI * 2); ctx.fill(); ctx.globalAlpha = 1; }
function drawPlatform(platform) { ctx.fillStyle = '#446c49'; ctx.fillRect(platform.x, platform.y, platform.w, platform.h); ctx.fillStyle = '#214f3f'; ctx.fillRect(platform.x, platform.y + 13, platform.w, platform.h - 13); ctx.fillStyle = '#aed36f'; ctx.fillRect(platform.x, platform.y, platform.w, 13); for (let x = platform.x + 18; x < platform.x + platform.w; x += 35) { ctx.fillStyle = '#376443'; ctx.fillRect(x, platform.y + 35, 3, 22); } }
function drawCoin(coin) { const scale = .35 + Math.abs(Math.cos(coin.spin)) * .65; ctx.save(); ctx.translate(coin.x, coin.y); ctx.scale(scale, 1); ctx.fillStyle = '#ffd84e'; ctx.beginPath(); ctx.arc(0, 0, 14, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#ffef93'; ctx.beginPath(); ctx.arc(-3, -4, 4, 0, Math.PI * 2); ctx.fill(); ctx.restore(); }
function drawEnemy(enemy) { ctx.fillStyle = '#d95f55'; ctx.beginPath(); ctx.roundRect(enemy.x, enemy.y, enemy.w, enemy.h, 12); ctx.fill(); ctx.fillStyle = '#183d36'; ctx.fillRect(enemy.x + 8, enemy.y + 12, 6, 7); ctx.fillRect(enemy.x + 24, enemy.y + 12, 6, 7); ctx.fillStyle = '#ffb169'; ctx.fillRect(enemy.x + 7, enemy.y + 31, 24, 5); }
function drawPlayer() { ctx.fillStyle = '#ff8155'; ctx.beginPath(); ctx.roundRect(player.x, player.y, player.w, player.h, 12); ctx.fill(); ctx.fillStyle = '#183d36'; ctx.fillRect(player.x + 21, player.y + 15, 6, 7); ctx.fillStyle = '#d8f36a'; ctx.fillRect(player.x - 4, player.y - 7, 42, 10); ctx.fillStyle = '#f5f1e7'; ctx.fillRect(player.x + 20, player.y + 28, 10, 4); }
function drawFlag() { ctx.fillStyle = '#183d36'; ctx.fillRect(3500, 360, 7, 200); ctx.fillStyle = '#ff8155'; ctx.beginPath(); ctx.moveTo(3507, 365); ctx.lineTo(3600, 390); ctx.lineTo(3507, 420); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#d8f36a'; ctx.beginPath(); ctx.arc(3503, 350, 14, 0, Math.PI * 2); ctx.fill(); }
function loop(time) { const dt = Math.min((time - lastTime) / 1000, .033); lastTime = time; if (running) { update(dt); draw(); animationId = requestAnimationFrame(loop); } }
window.addEventListener('keydown', (event) => { keys[event.key] = true; if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', ' '].includes(event.key)) event.preventDefault(); if ((event.key === ' ' || event.key === 'ArrowUp' || event.key === 'w') && player && player.grounded && running) { player.vy = -12; player.grounded = false; } });
window.addEventListener('keyup', (event) => { keys[event.key] = false; });
document.querySelector('#play-button').addEventListener('click', startGame); document.querySelector('#again-button').addEventListener('click', startGame); resetGame(); draw();